/*==============================================================================
  Copyright (c) 2016, 2017, 2018 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

#ifndef ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_HPP_
#define ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_HPP_

#include <argot/receiver/graphviz/detail/property_decl.hpp>

namespace argot {
namespace receiver {
namespace graphviz {
namespace edge_property {

#define ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( name_ )           \
ARGOT_RECEIVER_GRAPHVIZ_DETAIL_PROPERTY_DECL( edge, name_ )

ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( URL );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( arrowhead );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( arrowsize );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( arrowtail );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( color );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( colorscheme );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( comment );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( constraint );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( decorate );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( dir );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( edgeURL );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( edgehref );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( edgetarget );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( edgetooltip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( fillcolor );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( fontcolor );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( fontname );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( fontsize );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headURL );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( head_lp );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headclip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headhref );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headlabel );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headport );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headtarget );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( headtooltip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( href );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( id );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( label );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelURL );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelangle );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labeldistance );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelfloat );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelfontcolor );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelfontname );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelfontsize );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labelhref );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labeltarget );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( labeltooltip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( layer );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( len );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( lhead );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( lp );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( ltail );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( minlen );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( nojustify );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( penwidth );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( pos );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( samehead );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( sametail );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( showboxes );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( style );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailURL );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tail_lp );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailclip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailhref );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( taillabel );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailport );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailtarget );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tailtooltip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( target );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( tooltip );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( weight );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( xlabel );
ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_DECL( xlp );

} // namespace argot::receiver::graphviz::edge_property
} // namespace argot::receiver::graphviz
} // namespace argot::receiver
} // namespace argot

#endif  // ARGOT_RECEIVER_GRAPHVIZ_EDGE_PROPERTY_HPP_
