/*==============================================================================
  Copyright (c) 2016, 2017, 2018 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

#ifndef ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_HPP_
#define ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_HPP_

#include <argot/receiver/graphviz/detail/property_decl.hpp>

namespace argot {
namespace receiver {
namespace graphviz {
namespace graph_property {

#define ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( name_ )          \
ARGOT_RECEIVER_GRAPHVIZ_DETAIL_PROPERTY_DECL( graph, name_ )

ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( Damping );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( K );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( URL );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( _background );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( bb );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( bgcolor );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( center );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( charset );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( clusterrank );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( colorscheme );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( comment );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( compound );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( concentrate );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( defaultdist );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( dim );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( dimen );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( diredgeconstraints );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( dpi );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( epsilon );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( esep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( fontcolor );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( fontname );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( fontnames );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( fontpath );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( fontsize );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( forcelabels );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( gradientangle );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( href );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( id );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( imagepath );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( inputscale );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( label );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( label_scheme );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( labeljust );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( labelloc );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( landscape );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( layerlistsep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( layers );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( layerselect );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( layersep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( layout );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( levels );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( levelsgap );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( lheight );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( lp );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( lwidth );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( margin );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( maxiter );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( mclimit );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( mindist );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( mode );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( model );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( mosek );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( nodesep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( nojustify );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( normalize );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( notranslate );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( nslimit1 );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( ordering );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( orientation );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( outputorder );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( overlap );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( overlap_scaling );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( overlap_shrink );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( pack );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( packmode );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( pad );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( page );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( pagedir );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( quadtree );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( quantum );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( rankdir );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( ranksep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( ratio );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( remincross );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( repulsiveforce );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( resolution );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( root );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( rotate );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( rotation );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( scale );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( searchsize );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( sep );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( showboxes );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( size );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( smoothing );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( sortv );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( splines );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( start );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( style );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( stylesheet );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( target );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( truecolor );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( viewport );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( voro_margin );
ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_DECL( xdotversion );

}  // namespace argot::receiver::graphviz::graph_property
}  // namespace argot::receiver::graphviz
}  // namespace argot::receiver
}  // namespace argot

#endif  // ARGOT_RECEIVER_GRAPHVIZ_GRAPH_PROPERTY_HPP_
