/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_ASYNC_CALL_HPP_
#define ARGOT_ASYNC_CALL_HPP_

//[description"
/*`
This header includes all of the facilities of the `async_call` directory.
*/
//]

//[docs
//]

#include <argot/async_call/async_call.hpp>
#include <argot/async_call/async_call_.hpp>

#endif  // ARGOT_ASYNC_CALL_HPP_
