/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_CONC_HPP_
#define ARGOT_CONC_HPP_

//[description"
/*`
This header includes all of the facilities of the `conc` directory.
*/
//]

//[docs
//]

#include <argot/conc/alternative_of_by_value.hpp>
#include <argot/conc/bind_call.hpp>
#include <argot/conc/bless.hpp>
#include <argot/conc/bless_result.hpp>
#include <argot/conc/conc_generator.hpp>
#include <argot/conc/default_to_value_of.hpp>
#include <argot/conc/expand.hpp>
#include <argot/conc/group.hpp>
#include <argot/conc/lift.hpp>
#include <argot/conc/lift_call.hpp>
#include <argot/conc/lift_result.hpp>
#include <argot/conc/nothing.hpp>
#include <argot/conc/reference_to.hpp>
#include <argot/conc/unpack_by_value.hpp>
#include <argot/conc/value_of.hpp>
#include <argot/conc/when_ready.hpp>

#endif  // ARGOT_CONC_HPP_
