/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_CONC_TRAITS_HPP_
#define ARGOT_CONC_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `conc_traits` directory.
*/
//]

//[docs
//]

#include <argot/conc_traits/argument_list_kinds_of.hpp>
#include <argot/conc_traits/argument_list_kinds_of_destructive.hpp>
#include <argot/conc_traits/argument_list_kinds_of_persistent.hpp>
#include <argot/conc_traits/as_future.hpp>
#include <argot/conc_traits/destructive_forgetful_then_provide.hpp>
#include <argot/conc_traits/destructive_then_provide.hpp>
#include <argot/conc_traits/persistent_forgetful_then_provide.hpp>
#include <argot/conc_traits/persistent_then_provide.hpp>
#include <argot/conc_traits/then_provide.hpp>

#endif  // ARGOT_CONC_TRAITS_HPP_
