/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_EXECUTOR_HPP_
#define ARGOT_EXECUTOR_HPP_

//[description"
/*`
This header includes all of the facilities of the `executor` directory.
*/
//]

//[docs
//]

#include <argot/executor/defer_to.hpp>
#include <argot/executor/dispatch_to.hpp>
#include <argot/executor/immediate.hpp>
#include <argot/executor/post_to.hpp>
#include <argot/executor/stlab.hpp>

#endif  // ARGOT_EXECUTOR_HPP_
