/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_FUT_HPP_
#define ARGOT_FUT_HPP_

//[description"
/*`
This header includes all of the facilities of the `fut` directory.
*/
//]

//[docs
//]

#include <argot/fut/augment.hpp>
#include <argot/fut/future.hpp>
#include <argot/fut/ready.hpp>
#include <argot/fut/ready_as.hpp>
#include <argot/fut/squash.hpp>

#endif  // ARGOT_FUT_HPP_
