/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_FUT_TRAITS_HPP_
#define ARGOT_FUT_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `fut_traits` directory.
*/
//]

//[docs
//]

#include <argot/fut_traits/config.hpp>
#include <argot/fut_traits/destructive_forgetful_then.hpp>
#include <argot/fut_traits/destructive_then.hpp>
#include <argot/fut_traits/forgetful_then.hpp>
#include <argot/fut_traits/persistent_forgetful_then.hpp>
#include <argot/fut_traits/persistent_then.hpp>
#include <argot/fut_traits/then.hpp>
#include <argot/fut_traits/value_type.hpp>

#endif  // ARGOT_FUT_TRAITS_HPP_
