/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_GEN_HPP_
#define ARGOT_GEN_HPP_

//[description"
/*`
This header includes all of the facilities of the `gen` directory.
*/
//]

//[docs
//]

#include <argot/gen/access_raw_concept_map.hpp>
#include <argot/gen/and.hpp>
#include <argot/gen/auto_concept.hpp>
#include <argot/gen/concept_assert.hpp>
#include <argot/gen/concept_conditional.hpp>
#include <argot/gen/concept_ensure.hpp>
#include <argot/gen/concept_map_is_valid.hpp>
#include <argot/gen/explicit_concept.hpp>
#include <argot/gen/is_auto_concept.hpp>
#include <argot/gen/is_modeled.hpp>
#include <argot/gen/make_concept_map.hpp>
#include <argot/gen/not.hpp>
#include <argot/gen/or.hpp>
#include <argot/gen/requires.hpp>
#include <argot/gen/transparent_requirement.hpp>
#include <argot/gen/type.hpp>

#endif  // ARGOT_GEN_HPP_
