/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_OPAQUE_OPTIONAL_HPP_
#define ARGOT_OPAQUE_OPTIONAL_HPP_

//[description"
/*`
This header includes all of the facilities of the `opaque_optional` directory.
*/
//]

//[docs
//]

#include <argot/opaque_optional/copyable_opaque_optional.hpp>
#include <argot/opaque_optional/opaque_optional.hpp>

#endif  // ARGOT_OPAQUE_OPTIONAL_HPP_
