/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_OPT_TRAITS_HPP_
#define ARGOT_OPT_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `opt_traits` directory.
*/
//]

//[docs
//]

#include <argot/opt_traits/element_type.hpp>
#include <argot/opt_traits/get.hpp>
#include <argot/opt_traits/has_value.hpp>
#include <argot/opt_traits/nil.hpp>
#include <argot/opt_traits/nil_element_type.hpp>

#endif  // ARGOT_OPT_TRAITS_HPP_
