/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_PACKAGER_HPP_
#define ARGOT_PACKAGER_HPP_

//[description"
/*`
This header includes all of the facilities of the `packager` directory.
*/
//]

//[docs
//]

#include <argot/packager/boost_future.hpp>
#include <argot/packager/boost_shared_future.hpp>
#include <argot/packager/packager_base.hpp>
#include <argot/packager/packager_template.hpp>
#include <argot/packager/stlab.hpp>

#endif  // ARGOT_PACKAGER_HPP_
