/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_PACKAGER_TRAITS_HPP_
#define ARGOT_PACKAGER_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `packager_traits` directory.
*/
//]

//[docs
//]

#include <argot/packager_traits/package.hpp>

#endif  // ARGOT_PACKAGER_TRAITS_HPP_
