/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_RECEIVER_HPP_
#define ARGOT_RECEIVER_HPP_

//[description"
/*`
This header includes all of the facilities of the `receiver` directory.
*/
//]

//[docs
//]

#include <argot/receiver/do_nothing.hpp>
#include <argot/receiver/forgetful_invoke.hpp>
#include <argot/receiver/forward_result_to.hpp>
#include <argot/receiver/forward_transformed_arguments.hpp>
#include <argot/receiver/graphviz_dot.hpp>
#include <argot/receiver/nested_receiver.hpp>
#include <argot/receiver/provide_arguments_to.hpp>
#include <argot/receiver/receiver_reference.hpp>
#include <argot/receiver/reduced_invoke.hpp>
#include <argot/receiver/return_argument_list_kinds.hpp>
#include <argot/receiver/return_argument_references.hpp>
#include <argot/receiver/return_argument_values.hpp>
#include <argot/receiver/return_graphviz_dot.hpp>
#include <argot/receiver/return_single_argument_value.hpp>
#include <argot/receiver/with_leading_arguments.hpp>
#include <argot/receiver/with_leading_values.hpp>
#include <argot/receiver/with_trailing_concurrent_provider.hpp>
#include <argot/receiver/with_trailing_provider.hpp>

#endif  // ARGOT_RECEIVER_HPP_
