/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_REDUCER_HPP_
#define ARGOT_REDUCER_HPP_

//[description"
/*`
This header includes all of the facilities of the `reducer` directory.
*/
//]

//[docs
//]

#include <argot/reducer/graphviz_dot.hpp>
#include <argot/reducer/provide_result_to.hpp>
#include <argot/reducer/reducer_reference.hpp>
#include <argot/reducer/same_type_or_fail.hpp>
#include <argot/reducer/to.hpp>
#include <argot/reducer/to_boost_variant.hpp>
#include <argot/reducer/to_heterogeneous_variant.hpp>
#include <argot/reducer/to_variant.hpp>
#include <argot/reducer/transform.hpp>

#endif  // ARGOT_REDUCER_HPP_
