/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_REDUCER_TRAITS_HPP_
#define ARGOT_REDUCER_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `reducer_traits` directory.
*/
//]

//[docs
//]

#include <argot/reducer_traits/destructive_reduce.hpp>
#include <argot/reducer_traits/is_homogeneous.hpp>
#include <argot/reducer_traits/persistent_reduce.hpp>
#include <argot/reducer_traits/reduce.hpp>
#include <argot/reducer_traits/return_types.hpp>
#include <argot/reducer_traits/return_types_of_call.hpp>

#endif  // ARGOT_REDUCER_TRAITS_HPP_
