/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_STATE_TRAITS_HPP_
#define ARGOT_STATE_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `state_traits` directory.
*/
//]

//[docs
//]

#include <argot/state_traits/equal_to.hpp>
#include <argot/state_traits/greater_equal.hpp>
#include <argot/state_traits/greater_than.hpp>
#include <argot/state_traits/hash.hpp>
#include <argot/state_traits/hash_combine.hpp>
#include <argot/state_traits/less_equal.hpp>
#include <argot/state_traits/less_than.hpp>
#include <argot/state_traits/not_equal_to.hpp>

#endif  // ARGOT_STATE_TRAITS_HPP_
