/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_TUPLE_TRAITS_HPP_
#define ARGOT_TUPLE_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `tuple_traits` directory.
*/
//]

//[docs
//]

#include <argot/tuple_traits/element_type.hpp>
#include <argot/tuple_traits/get.hpp>
#include <argot/tuple_traits/index_constant.hpp>
#include <argot/tuple_traits/index_type.hpp>
#include <argot/tuple_traits/natural_get.hpp>
#include <argot/tuple_traits/num_elements.hpp>

#endif  // ARGOT_TUPLE_TRAITS_HPP_
