/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_UNION_TRAITS_HPP_
#define ARGOT_UNION_TRAITS_HPP_

//[description"
/*`
This header includes all of the facilities of the `union_traits` directory.
*/
//]

//[docs
//]

#include <argot/union_traits/alternative_type.hpp>
#include <argot/union_traits/get.hpp>
#include <argot/union_traits/index_constant.hpp>
#include <argot/union_traits/index_type.hpp>
#include <argot/union_traits/natural_get.hpp>
#include <argot/union_traits/num_alternatives.hpp>

#endif  // ARGOT_UNION_TRAITS_HPP_
