/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_CONC_EXPAND_HPP_
#define ARGOT_CONC_EXPAND_HPP_

//[description"
/*`
This header includes all of the facilities of the `expand` directory.
*/
//]

//[docs
//]

#include <argot/conc/expand/expand.hpp>
#include <argot/conc/expand/expansion_operator.hpp>

#endif  // ARGOT_CONC_EXPAND_HPP_
