/*==============================================================================
  Copyright (c) 2020 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_HPP_
#define ARGOT_HPP_

//[description"
/*`
This header includes all of the facilities of the `argot` directory.
*/
//]

//[docs
//]

#include <argot/accumulate.hpp>
#include <argot/as_call_object.hpp>
#include <argot/async_call.hpp>
#include <argot/basic_result_of.hpp>
#include <argot/call.hpp>
#include <argot/call_object_base.hpp>
#include <argot/case.hpp>
#include <argot/compose.hpp>
#include <argot/conc.hpp>
#include <argot/conc_traits.hpp>
#include <argot/concepts.hpp>
#include <argot/config.hpp>
#include <argot/contained.hpp>
#include <argot/contextually_convert_to_bool.hpp>
#include <argot/convert_future.hpp>
#include <argot/default_.hpp>
#include <argot/discriminated_union.hpp>
#include <argot/empty_switch_body.hpp>
#include <argot/executor.hpp>
#include <argot/executor_traits.hpp>
#include <argot/forgetful_async_call.hpp>
#include <argot/forgetful_call.hpp>
#include <argot/forward_arguments_as_tuple.hpp>
#include <argot/fut.hpp>
#include <argot/fut_traits.hpp>
#include <argot/future_spawner.hpp>
#include <argot/future_traits.hpp>
#include <argot/gen.hpp>
#include <argot/identity.hpp>
#include <argot/impossible.hpp>
#include <argot/in_place_default_init.hpp>
#include <argot/in_place_index_with_result.hpp>
#include <argot/in_place_with_result.hpp>
#include <argot/invocable_reference.hpp>
#include <argot/lazy_expand.hpp>
#include <argot/no_unique_address.hpp>
#include <argot/opaque_optional.hpp>
#include <argot/operators.hpp>
#include <argot/opt_traits.hpp>
#include <argot/output.hpp>
#include <argot/packager.hpp>
#include <argot/packager_traits.hpp>
#include <argot/prov.hpp>
#include <argot/prov_traits.hpp>
#include <argot/receiver.hpp>
#include <argot/receiver_traits.hpp>
#include <argot/reducer.hpp>
#include <argot/reducer_traits.hpp>
#include <argot/referential_identity.hpp>
#include <argot/side_effect.hpp>
#include <argot/state_traits.hpp>
#include <argot/struct_.hpp>
#include <argot/switch_traits.hpp>
#include <argot/tag.hpp>
#include <argot/tuple_traits.hpp>
#include <argot/type_list.hpp>
#include <argot/union_.hpp>
#include <argot/union_traits.hpp>
#include <argot/unreachable_function.hpp>
#include <argot/value_list.hpp>
#include <argot/value_zipper.hpp>
#include <argot/variant_traits.hpp>
#include <argot/void_.hpp>
#include <argot/zipper.hpp>

#endif  // ARGOT_HPP_
