/*==============================================================================
  Copyright (c) 2019 Matt Calabrese

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/

/******************************************************************************/
/******** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY BY HAND. ********/
/******************************************************************************/

#ifndef ARGOT_PROV_BIND_TRANSFORM_HPP_
#define ARGOT_PROV_BIND_TRANSFORM_HPP_

//[description"
/*`
This header includes all of the facilities of the `bind_transform` directory.
*/
//]

//[docs
//]

#include <argot/prov/bind_transform/bind_transform.hpp>
#include <argot/prov/bind_transform/operator_pipe.hpp>

#endif  // ARGOT_PROV_BIND_TRANSFORM_HPP_
